files:
  circleci.handlebars:
    templateType: SupportingFiles
    destinationFilename: .circleci/config.yml
  api_metrics.handlebars:
    templateType: SupportingFiles
    destinationFilename: {{packageName}}/api_metrics.py
  api_timeout.handlebars:
    templateType: SupportingFiles
    destinationFilename: {{packageName}}/api_timeout.py
  api_auth.handlebars:
    templateType: SupportingFiles
    destinationFilename: {{packageName}}/api_auth.py
  pyproject.handlebars:
    templateType: SupportingFiles
    destinationFilename: pyproject.toml
  check.handlebars:
    folder: scripts
    templateType: SupportingFiles
    destinationFilename: check.sh
  publish.handlebars:
    folder: scripts
    templateType: SupportingFiles
    destinationFilename: publish.sh
