version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
  python: circleci/python@2.1.1
  bm-secrets-detection: backmarket/bm-secrets-detection@1

alias:
  default_context: &default_context
    context:
      - bm-private-ecr
      - SonarCloud

executors:
  python:
    docker:
      - image: 154005363564.dkr.ecr.us-east-1.amazonaws.com/docker.io/cimg/python:3.10.8
    resource_class: small
    working_directory: .
  cimg:
    docker:
      - image: 154005363564.dkr.ecr.us-east-1.amazonaws.com/docker.io/cimg/base:2022.11
    resource_class: small
    working_directory: .

commands:
  checkout-repo:
    description: Shallow clone repository
    steps:
      - git-shallow-clone/checkout
  python-install-deps:
    description: Install python dependencies
    steps:
      - python/install-packages:
          pkg-manager: poetry
      - run: echo 'export PATH=$(poetry env info --path)/bin:$PATH' >> $BASH_ENV

jobs:
  generate_client:
    # TODO: check if we can replace this with a docker executor instead of a machine
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - checkout-repo
      - run: make generate-openapi-client
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - openapi_client
            - pyproject.toml
            - poetry.lock
            - Makefile
  check-tests-were-generated:
    executor: cimg
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run: grep -r assert openapi_client/test
  test:
    executor: python
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - python-install-deps
      - run: make test

workflows:
  version: 2
  main-workflow:
    jobs:
      - generate_client:
          <<: *default_context
      - check-tests-were-generated:
          <<: *default_context
          requires:
            - generate_client
      - test:
          <<: *default_context
          requires:
            - generate_client
      - bm-secrets-detection/scan:
          fail: true
